// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtceQ8Lpa8XSlpRNRh5JNhOnPQXb8G6aA',
    appId: '1:100942407983:android:60b5dd000a9631805399da',
    messagingSenderId: '100942407983',
    projectId: 'vantage-d34a2',
    storageBucket: 'vantage-d34a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8H2A_MRcicfFxUKQno6-qGRjuMzUHTwE',
    appId: '1:100942407983:ios:b79c0ad4c0deca6b5399da',
    messagingSenderId: '100942407983',
    projectId: 'vantage-d34a2',
    storageBucket: 'vantage-d34a2.firebasestorage.app',
    iosClientId: '100942407983-jk7aq1fenbfpk8c9mngbh61o6nhj2lcf.apps.googleusercontent.com',
    iosBundleId: 'com.vantage.app.vantage',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg6ylJ_venXgzxUVDjHW2gxwVrQ5Yy860',
    appId: '1:100942407983:web:1a4aee31d03fa58f5399da',
    messagingSenderId: '100942407983',
    projectId: 'vantage-d34a2',
    authDomain: 'vantage-d34a2.firebaseapp.com',
    storageBucket: 'vantage-d34a2.firebasestorage.app',
    measurementId: 'G-SY0DNVP33F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8H2A_MRcicfFxUKQno6-qGRjuMzUHTwE',
    appId: '1:100942407983:ios:b79c0ad4c0deca6b5399da',
    messagingSenderId: '100942407983',
    projectId: 'vantage-d34a2',
    storageBucket: 'vantage-d34a2.firebasestorage.app',
    iosClientId: '100942407983-jk7aq1fenbfpk8c9mngbh61o6nhj2lcf.apps.googleusercontent.com',
    iosBundleId: 'com.vantage.app.vantage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg6ylJ_venXgzxUVDjHW2gxwVrQ5Yy860',
    appId: '1:100942407983:web:863a4c4c1ccbb5055399da',
    messagingSenderId: '100942407983',
    projectId: 'vantage-d34a2',
    authDomain: 'vantage-d34a2.firebaseapp.com',
    storageBucket: 'vantage-d34a2.firebasestorage.app',
    measurementId: 'G-WCX5X59QWD',
  );

}